string = input(' Masukkan kalimat : ')
low = string.lower()
print(low)
count = string.count(string)
print("banyak string ada", count)
cap = string.capitalize()
print(cap)
up = string.upper()
print(up)
huruf1 = string.count('i')
print ('banyak huruf i : ', huruf1)
huruf2 = string.count('a')
print ('banyak huruf a : ', huruf2)
huruf3 = string.count('n')
print ('banyak huruf n : ', huruf3)
huruf4 = string.count('d')
print ('banyak huruf d : ', huruf4)

